
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Random;

/*******************************************************************************
This program plays all of the conference teams against each other two times, 
and then against the non-conference teams once. Then it displays the season
results of each team in descending order of their record and displays their
status in the last column.
@author Eric malcolm, Section 001
*******************************************************************************/

public class MarchMadness extends javax.swing.JFrame {

    /**
     * Creates new form MarchMadness
     */
    public MarchMadness() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTopLeft = new javax.swing.JPanel();
        lblConferenceTeams = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listConferenceTeams = new javax.swing.JList<>();
        pnlBottomLeft = new javax.swing.JPanel();
        lblNonConferenceTeams = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNonConferenceTeams = new javax.swing.JList<>();
        pnlRight = new javax.swing.JPanel();
        lblRecord = new javax.swing.JLabel();
        lblWins = new javax.swing.JLabel();
        lblLosses = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblTeam1 = new javax.swing.JLabel();
        lblTeam2 = new javax.swing.JLabel();
        lblTeam3 = new javax.swing.JLabel();
        lblTeam4 = new javax.swing.JLabel();
        lblTeam5 = new javax.swing.JLabel();
        lblTeam6 = new javax.swing.JLabel();
        lblTeam7 = new javax.swing.JLabel();
        lblTeam8 = new javax.swing.JLabel();
        lblTeam9 = new javax.swing.JLabel();
        lblTeam10 = new javax.swing.JLabel();
        lblWin1 = new javax.swing.JLabel();
        lblWin2 = new javax.swing.JLabel();
        lblWin3 = new javax.swing.JLabel();
        lblWin4 = new javax.swing.JLabel();
        lblWin5 = new javax.swing.JLabel();
        lblWin6 = new javax.swing.JLabel();
        lblWin7 = new javax.swing.JLabel();
        lblWin8 = new javax.swing.JLabel();
        lblWin9 = new javax.swing.JLabel();
        lblWin10 = new javax.swing.JLabel();
        lblLosses1 = new javax.swing.JLabel();
        lblLosses2 = new javax.swing.JLabel();
        lblLosses3 = new javax.swing.JLabel();
        lblLosses4 = new javax.swing.JLabel();
        lblLosses5 = new javax.swing.JLabel();
        lblLosses6 = new javax.swing.JLabel();
        lblLosses7 = new javax.swing.JLabel();
        lblLosses8 = new javax.swing.JLabel();
        lblLosses9 = new javax.swing.JLabel();
        lblLosses10 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        lblStatus3 = new javax.swing.JLabel();
        lblStatus4 = new javax.swing.JLabel();
        lblStatus5 = new javax.swing.JLabel();
        lblStatus6 = new javax.swing.JLabel();
        lblStatus7 = new javax.swing.JLabel();
        lblStatus8 = new javax.swing.JLabel();
        lblStatus9 = new javax.swing.JLabel();
        lblStatus10 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        ckbHomeAdv = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("March Madness");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTopLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTopLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConferenceTeams.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        lblConferenceTeams.setText("Conference Teams");
        pnlTopLeft.add(lblConferenceTeams, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        listConferenceTeams.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BYU", "Gonzaga", "Loyola", "St. Marys", "Pepperdine", "San Francisco", "San Diego", "Portland", "Pacific", "Santa Clara" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listConferenceTeams.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listConferenceTeams.setSelectedIndex(0);
        jScrollPane1.setViewportView(listConferenceTeams);

        pnlTopLeft.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 200));

        pnlMain.add(pnlTopLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 230));

        pnlBottomLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBottomLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNonConferenceTeams.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        lblNonConferenceTeams.setText("Non-Conference Teams");
        pnlBottomLeft.add(lblNonConferenceTeams, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        listNonConferenceTeams.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Arizona", "Florida", "Memphis", "Stanford", "Dayton", "Texas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listNonConferenceTeams.setSelectedIndex(0);
        jScrollPane2.setViewportView(listNonConferenceTeams);

        pnlBottomLeft.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 120));

        pnlMain.add(pnlBottomLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 160));

        pnlRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRecord.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        lblRecord.setText("Record");
        pnlRight.add(lblRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblWins.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        lblWins.setText("Wins");
        pnlRight.add(lblWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        lblLosses.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        lblLosses.setText("Losses");
        pnlRight.add(lblLosses, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        lblStatus.setFont(new java.awt.Font("Lucida Grande", 3, 12)); // NOI18N
        lblStatus.setText("Status");
        pnlRight.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lblTeam1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblTeam2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblTeam3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblTeam4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblTeam5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblTeam6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblTeam7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblTeam8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblTeam9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblTeam10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblTeam10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblWin1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        lblWin2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        lblWin3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        lblWin4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        lblWin5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        lblWin6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lblWin7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        lblWin8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        lblWin9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        lblWin10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblWin10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        lblLosses1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        lblLosses2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        lblLosses3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        lblLosses4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        lblLosses5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        lblLosses6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        lblLosses7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        lblLosses8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        lblLosses9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        lblLosses10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblLosses10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        lblStatus1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        lblStatus2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        lblStatus3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        lblStatus4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        lblStatus5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        lblStatus6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        lblStatus7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        lblStatus8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        lblStatus9.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        lblStatus10.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        pnlRight.add(lblStatus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        pnlMain.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 430, 260));

        btnPlay.setText("Play");
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnlMain.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        pnlMain.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, -1, -1));

        btnQuit.setText("Quit");
        btnQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitMouseClicked(evt);
            }
        });
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        pnlMain.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        ckbHomeAdv.setText("Home Team +5");
        pnlMain.add(ckbHomeAdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitMouseClicked
        //quits the program
        System.exit(0);
    }//GEN-LAST:event_btnQuitMouseClicked

    private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
        ArrayList<BasketballTeam> team = new ArrayList<BasketballTeam>();
        Random scoreGenerator = new Random();

        //gets all the names and creates BasketballTeam objects
        for (int i = 0; i < listConferenceTeams.getModel().getSize(); i++) {
            team.add(new BasketballTeam(listConferenceTeams.getModel().getElementAt(i)));

        }

        int iHomeScore = 0, iOppScore = 0;
        boolean homeTeamAdv = true;

        //plays each of the conference teams twice
        for (int k = 0; k < listConferenceTeams.getModel().getSize(); k++) {
            for (int i = 1; i < listConferenceTeams.getModel().getSize(); i++) {
                for (int j = 0; j < 2; j++) {
                    do {
                        iHomeScore = scoreGenerator.nextInt(100);
                        iOppScore = scoreGenerator.nextInt(100);
                        if (ckbHomeAdv.isSelected() && homeTeamAdv) {
                            iHomeScore += 5;
                            homeTeamAdv = false;
                        }
                        else if (ckbHomeAdv.isSelected() && !homeTeamAdv) {
                            iOppScore += 5;
                            homeTeamAdv = true;
                        }                        
                    } while (iHomeScore == iOppScore);
                    if (iHomeScore > iOppScore) {
                        team.get(k).setWins(team.get(k).wins + 1);
                    } else {
                        team.get(k).setLosses(team.get(k).losses + 1);
                    }
                }
            }
        }

        //plays the non-conference teams once
        for (int i = 0; i < listConferenceTeams.getModel().getSize(); i++) {
            for (int j = 0; j < listNonConferenceTeams.getModel().getSize(); j++) {
                do {
                    iHomeScore = scoreGenerator.nextInt(100);
                    iOppScore = scoreGenerator.nextInt(100);
                } while (iHomeScore == iOppScore);
                if (iHomeScore > iOppScore) {
                    team.get(i).setWins(team.get(i).wins + 1);
                } else {
                    team.get(i).setLosses(team.get(i).losses + 1);
                }
            }
        }

        //sorts the arraylist descending
        Collections.sort(team, new Comparator<BasketballTeam>() {
            public int compare(BasketballTeam t1, BasketballTeam t2) {
                return Integer.valueOf(t2.wins).compareTo(t1.wins);
            }
        });
        
        //assigns status
        for(int i = 0; i < listConferenceTeams.getModel().getSize(); i++) {
            if(team.get(i).wins > 17) {
                team.get(i).setStatus("March Madness");
            }
            else if (team.get(i).wins > 14) {
                team.get(i).setStatus("NIT");
            }
            else {
                team.get(i).setStatus("See you next year");
            }
        }
        
        //sets the name lables
        lblTeam1.setText(team.get(0).teamName);
        lblTeam2.setText(team.get(1).teamName);
        lblTeam3.setText(team.get(2).teamName);
        lblTeam4.setText(team.get(3).teamName);
        lblTeam5.setText(team.get(4).teamName);
        lblTeam6.setText(team.get(5).teamName);
        lblTeam7.setText(team.get(6).teamName);
        lblTeam8.setText(team.get(7).teamName);
        lblTeam9.setText(team.get(8).teamName);
        lblTeam10.setText(team.get(9).teamName);
        
        //sets the win labels
        lblWin1.setText(String.valueOf(team.get(0).wins));
        lblWin2.setText(String.valueOf(team.get(1).wins));
        lblWin3.setText(String.valueOf(team.get(2).wins));
        lblWin4.setText(String.valueOf(team.get(3).wins));
        lblWin5.setText(String.valueOf(team.get(4).wins));
        lblWin6.setText(String.valueOf(team.get(5).wins));
        lblWin7.setText(String.valueOf(team.get(6).wins));
        lblWin8.setText(String.valueOf(team.get(7).wins));
        lblWin9.setText(String.valueOf(team.get(8).wins));
        lblWin10.setText(String.valueOf(team.get(9).wins));
        
        //sets the losses labels
        lblLosses1.setText(String.valueOf(team.get(0).losses));
        lblLosses2.setText(String.valueOf(team.get(1).losses));
        lblLosses3.setText(String.valueOf(team.get(2).losses));
        lblLosses4.setText(String.valueOf(team.get(3).losses));
        lblLosses5.setText(String.valueOf(team.get(4).losses));
        lblLosses6.setText(String.valueOf(team.get(5).losses));
        lblLosses7.setText(String.valueOf(team.get(6).losses));
        lblLosses8.setText(String.valueOf(team.get(7).losses));
        lblLosses9.setText(String.valueOf(team.get(8).losses));
        lblLosses10.setText(String.valueOf(team.get(9).losses)); 
        
        //set the statuses
        lblStatus1.setText(team.get(0).getStatus());
        lblStatus2.setText(team.get(1).getStatus());
        lblStatus3.setText(team.get(2).getStatus());
        lblStatus4.setText(team.get(3).getStatus());
        lblStatus5.setText(team.get(4).getStatus());
        lblStatus6.setText(team.get(5).getStatus());
        lblStatus7.setText(team.get(6).getStatus());
        lblStatus8.setText(team.get(7).getStatus());
        lblStatus9.setText(team.get(8).getStatus());
        lblStatus10.setText(team.get(9).getStatus());
    }//GEN-LAST:event_btnPlayMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        //resets the name lables
        lblTeam1.setText("");
        lblTeam2.setText("");
        lblTeam3.setText("");
        lblTeam4.setText("");
        lblTeam5.setText("");
        lblTeam6.setText("");
        lblTeam7.setText("");
        lblTeam8.setText("");
        lblTeam9.setText("");
        lblTeam10.setText("");
        
        //sets the win labels
        lblWin1.setText("");
        lblWin2.setText("");
        lblWin3.setText("");
        lblWin4.setText("");
        lblWin5.setText("");
        lblWin6.setText("");
        lblWin7.setText("");
        lblWin8.setText("");
        lblWin9.setText("");
        lblWin10.setText("");
        
        //sets the losses labels
        lblLosses1.setText("");
        lblLosses2.setText("");
        lblLosses3.setText("");
        lblLosses4.setText("");
        lblLosses5.setText("");
        lblLosses6.setText("");
        lblLosses7.setText("");
        lblLosses8.setText("");
        lblLosses9.setText("");
        lblLosses10.setText(""); 
        
        //set the statuses
        lblStatus1.setText("");
        lblStatus2.setText("");
        lblStatus3.setText("");
        lblStatus4.setText("");
        lblStatus5.setText("");
        lblStatus6.setText("");
        lblStatus7.setText("");
        lblStatus8.setText("");
        lblStatus9.setText("");
        lblStatus10.setText("");
        
        //reset the checkbox
        ckbHomeAdv.setSelected(false);
    }//GEN-LAST:event_btnResetMouseClicked
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarchMadness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarchMadness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarchMadness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarchMadness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarchMadness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox ckbHomeAdv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConferenceTeams;
    private javax.swing.JLabel lblLosses;
    private javax.swing.JLabel lblLosses1;
    private javax.swing.JLabel lblLosses10;
    private javax.swing.JLabel lblLosses2;
    private javax.swing.JLabel lblLosses3;
    private javax.swing.JLabel lblLosses4;
    private javax.swing.JLabel lblLosses5;
    private javax.swing.JLabel lblLosses6;
    private javax.swing.JLabel lblLosses7;
    private javax.swing.JLabel lblLosses8;
    private javax.swing.JLabel lblLosses9;
    private javax.swing.JLabel lblNonConferenceTeams;
    private javax.swing.JLabel lblRecord;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblStatus10;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JLabel lblStatus3;
    private javax.swing.JLabel lblStatus4;
    private javax.swing.JLabel lblStatus5;
    private javax.swing.JLabel lblStatus6;
    private javax.swing.JLabel lblStatus7;
    private javax.swing.JLabel lblStatus8;
    private javax.swing.JLabel lblStatus9;
    private javax.swing.JLabel lblTeam1;
    private javax.swing.JLabel lblTeam10;
    private javax.swing.JLabel lblTeam2;
    private javax.swing.JLabel lblTeam3;
    private javax.swing.JLabel lblTeam4;
    private javax.swing.JLabel lblTeam5;
    private javax.swing.JLabel lblTeam6;
    private javax.swing.JLabel lblTeam7;
    private javax.swing.JLabel lblTeam8;
    private javax.swing.JLabel lblTeam9;
    private javax.swing.JLabel lblWin1;
    private javax.swing.JLabel lblWin10;
    private javax.swing.JLabel lblWin2;
    private javax.swing.JLabel lblWin3;
    private javax.swing.JLabel lblWin4;
    private javax.swing.JLabel lblWin5;
    private javax.swing.JLabel lblWin6;
    private javax.swing.JLabel lblWin7;
    private javax.swing.JLabel lblWin8;
    private javax.swing.JLabel lblWin9;
    private javax.swing.JLabel lblWins;
    private javax.swing.JList<String> listConferenceTeams;
    private javax.swing.JList<String> listNonConferenceTeams;
    private javax.swing.JPanel pnlBottomLeft;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTopLeft;
    // End of variables declaration//GEN-END:variables
}
